name             'bithub'
maintainer       'Nikica Jokic'
maintainer_email 'neektza@gmail.com'
license          'All rights reserved'
description      'Installs/Configures Bithub'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.2'

depends 'rbenv'
depends 'imagemagick'
depends 'database'
depends 'postgresql'
depends 'nginx'
depends 'rabbitmq', '> 2.3'
depends 'vim'
depends 'tmux'
